### ISSUE TITLE
Holiday Wishes...

### ISSUE THREAD

**Issue by Ibuprophen** [creativetrendsapps/Creative-Trends-Updates#1]
I just wanted to wish @creativetrendsapps Family and Friends the Best Wishes, Happy Holidays and a Happy New Year!!! 

I hope this year ends even more Uplifting and Promising as the last (bumpy) year has ended with!! 

Take care My Friend. 

~Ibuprophen

**Comment by creativetrendsapps** [comment]
Thanks.
